/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "plugin",
      "frontmatter": {
        "title": "plugin",
        "date": "2020-05-28T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/plugin.html",
      "relativePath": "theme-reco/plugin.md",
      "key": "v-77b74740",
      "path": "/theme-reco/plugin.html"
    },
    {
      "title": "abc",
      "frontmatter": {
        "title": "abc",
        "date": "2020-05-29T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/api.html",
      "relativePath": "theme-reco/api.md",
      "key": "v-416bdab0",
      "path": "/theme-reco/api.html"
    },
    {
      "title": "theme",
      "frontmatter": {
        "title": "theme",
        "date": "2020-05-27T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/theme.html",
      "relativePath": "theme-reco/theme.md",
      "key": "v-0030ed12",
      "path": "/theme-reco/theme.html"
    },
    {
      "title": "theme-reco",
      "frontmatter": {
        "title": "theme-reco",
        "date": "2020-05-29T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/",
      "relativePath": "theme-reco/README.md",
      "key": "v-5bf142aa",
      "path": "/theme-reco/"
    }
  ],
  "themeConfig": {}
}